import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const statesData = [
    {
        "name": "Abuja",
        "capital": "Abuja",
        "latitude": 8.8311228,
        "longitude": 7.1724673
    },
    {
        "name": "Abia",
        "capital": "Umuahia",
        "latitude": 5.4540953,
        "longitude": 7.5153071
    },
    {
        "name": "Adamawa",
        "capital": "Yola",
        "latitude": 9.5129772,
        "longitude": 12.3881887
    },
    {
        "name": "Akwa Ibom",
        "capital": "Uyo",
        "latitude": 4.9408638,
        "longitude": 7.8412267
    },
    {
        "name": "Anambra",
        "capital": "Awka",
        "latitude": 6.2183136,
        "longitude": 6.9531842
    },
    {
        "name": "Bauchi",
        "capital": "Bauchi",
        "latitude": 10.6228284,
        "longitude": 10.0287754
    },
    {
        "name": "Bayelsa",
        "capital": "Yenagoa",
        "latitude": 4.7629786,
        "longitude": 6.028898
    },
    {
        "name": "Benue",
        "capital": "Makurdi",
        "latitude": 7.3505747,
        "longitude": 8.7772877
    },
    {
        "name": "Borno",
        "capital": "Maiduguri",
        "latitude": 12.1875392,
        "longitude": 13.3080034
    },
    {
        "name": "Cross River",
        "capital": "Calabar",
        "latitude": 5.8671966,
        "longitude": 8.5204774
    },
    {
        "name": "Delta",
        "capital": "Asaba",
        "latitude": 5.5273061,
        "longitude": 6.1784167
    },
    {
        "name": "Ebonyi",
        "capital": "Abakaliki",
        "latitude": 6.1996918,
        "longitude": 8.0348906
    },
    {
        "name": "Edo",
        "capital": "Benin City",
        "latitude": 6.6076575,
        "longitude": 5.9722713
    },
    {
        "name": "Ekiti",
        "capital": "Ado-Ekiti",
        "latitude": 7.736891,
        "longitude": 5.2738326
    },
    {
        "name": "Enugu",
        "capital": "Enugu",
        "latitude": 6.5536094,
        "longitude": 7.4143061
    },
    {
        "name": "Gombe",
        "capital": "Gombe",
        "latitude": 10.38301,
        "longitude": 11.206567
    },
    {
        "name": "Imo",
        "capital": "Owerri",
        "latitude": 5.5859456,
        "longitude": 7.0669651
    },
    {
        "name": "Jigawa",
        "capital": "Dutse",
        "latitude": 12.3252362,
        "longitude": 9.5103296
    },
    {
        "name": "Kaduna",
        "capital": "Kaduna",
        "latitude": 10.3825318,
        "longitude": 7.8533226
    },
    {
        "name": "Kano",
        "capital": "Kano",
        "latitude": 11.8948389,
        "longitude": 8.5364136
    },
    {
        "name": "Katsina",
        "capital": "Katsina",
        "latitude": 12.5630825,
        "longitude": 7.6207063
    },
    {
        "name": "Kebbi",
        "capital": "Birnin-Kebbi",
        "latitude": 11.4167574,
        "longitude": 4.1074545
    },
    {
        "name": "Kogi",
        "capital": "Lokoja",
        "latitude": 7.79496,
        "longitude": 6.6868669
    },
    {
        "name": "Kwara",
        "capital": "Ilorin",
        "latitude": 8.8367891,
        "longitude": 4.6688487
    },
    {
        "name": "Lagos",
        "capital": "Ikeja",
        "latitude": 6.5269033,
        "longitude": 3.5774005
    },
    {
        "name": "Nassarawa",
        "capital": "Lafia",
        "latitude": 8.4387868,
        "longitude": 8.2382849
    },
    {
        "name": "Niger",
        "capital": "Minna",
        "latitude": 9.9326083,
        "longitude": 5.6511088
    },
    {
        "name": "Ogun",
        "capital": "Abeokuta",
        "latitude": 6.9788582,
        "longitude": 3.4389293
    },
    {
        "name": "Ondo",
        "capital": "Akure",
        "latitude": 7.0209686,
        "longitude": 5.0567477
    },
    {
        "name": "Osun",
        "capital": "Osogbo",
        "latitude": 7.5484047,
        "longitude": 4.4978307
    },
    {
        "name": "Oyo",
        "capital": "Ibadan",
        "latitude": 8.2151249,
        "longitude": 3.5642897
    },
    {
        "name": "Plateau",
        "capital": "Jos",
        "latitude": 9.0583446,
        "longitude": 9.6826289
    },
    {
        "name": "Rivers",
        "capital": "Port-Harcourt",
        "latitude": 4.8416028,
        "longitude": 6.8604088
    },
    {
        "name": "Sokoto",
        "capital": "Sokoto",
        "latitude": 13.0611195,
        "longitude": 5.3152203
    },
    {
        "name": "Taraba",
        "capital": "Jalingo",
        "latitude": 8.0141334,
        "longitude": 10.7376336
    },
    {
        "name": "Yobe",
        "capital": "Damaturu",
        "latitude": 12.1233242,
        "longitude": 11.5065937
    },
    {
        "name": "Zamfara",
        "capital": "Gusau",
        "latitude": 12.0078998,
        "longitude": 6.4191432
    }
];

const localGovernmentsData = {
    "Abia": [
        "Aba North",
        "Aba South",
        "Arochukwu",
        "Bende",
        "Ikwuano",
        "Isiala Ngwa North",
        "Isiala Ngwa South",
        "Isuikwuato",
        "Oboma Ngwa",
        "Ohafia",
        "Osisioma",
        "Ugwunagbo",
        "Ukwa East",
        "Ukwa West",
        "Umu-Nneochi",
        "Umuahia North",
        "Umuahia South"
    ],
    "Federal Capital Territory": [
        "Abaji",
        "Bwari",
        "Gwagwalada",
        "Kuje",
        "Kwali",
        "Municipal"
    ],
    "Adamawa": [
        "Demsa",
        "Fufore",
        "Ganye",
        "Girie",
        "Gombi",
        "Guyuk",
        "Hong",
        "Jada",
        "Lamurde",
        "Madagali",
        "Maiha",
        "Mayo-Belwa",
        "Michika",
        "Mubi North",
        "Mubi South",
        "Numan",
        "Shelleng",
        "Song",
        "Teungo",
        "Yola North",
        "Yola South"
    ],
    "Akwa Ibom": [
        "Abak",
        "Eastern Obolo",
        "Eket",
        "Esit Eket",
        "Essien Udim",
        "Etim Ekpo",
        "Etinan",
        "Ibeno",
        "Ibesikpo Asutan",
        "Ibiono Ibom",
        "Ika",
        "Ikono",
        "Ikot Abasi",
        "Ikot Ekpene",
        "Ini",
        "Itu",
        "Mbo",
        "Mkpat Enin",
        "Nsit Atai",
        "Nsit Ibom",
        "Nsit Ubium",
        "Obot Akara",
        "Okobo",
        "Onna",
        "Oron",
        "Oruk Anam",
        "Udung Uko",
        "Ukanafun",
        "Uruan",
        "Urue Offong|Oruko",
        "Uyo"
    ],
    "Anambra": [
        "Aguata",
        "Anambra East",
        "Anambra West",
        "Anaocha",
        "Awka North",
        "Awka South",
        "Ayamelum",
        "Dunukofia",
        "Ekwusigo",
        "Idemili North",
        "Idemili South",
        "Ihiala",
        "Njikoka",
        "Nnewi North",
        "Nnewi South",
        "Ogbaru",
        "Onitsha North",
        "Onitsha South",
        "Orumba North",
        "Orumba South",
        "Oyi"
    ],
    "Bauchi": [
        "Alkaleri",
        "Bauchi",
        "Bogoro",
        "Damban",
        "Darazo",
        "Dass",
        "Gamawa",
        "Gamjuwa",
        "Giade",
        "Itas/Gadau",
        "Jama'are",
        "Katagum",
        "Kirfi",
        "Misau",
        "Ningi",
        "Shira",
        "Tafawa-Balewa",
        "Toro",
        "Warji",
        "Zaki"
    ],
    "Bayelsa": [
        "Brass",
        "Ekeremor",
        "Kolokuma-Opokuma",
        "Nembe",
        "Ogbia",
        "Sagbama",
        "Southern Ijaw",
        "Yenagoa"
    ],
    "Benue": [
        "Ado",
        "Agatu",
        "Apa",
        "Buruku",
        "Gboko",
        "Guma",
        "Gwer East",
        "Gwer West",
        "Katsina- Ala",
        "Konshisha",
        "Kwande",
        "Logo",
        "Makurdi",
        "Obi",
        "Ogbadibo",
        "Ohimini",
        "Oju",
        "Okpokwu",
        "Oturkpo",
        "Tarka",
        "Ukum",
        "Ushongo",
        "Vandeikya"
    ],
    "Borno": [
        "Abadam",
        "Askira/Uba",
        "Bama",
        "Bayo",
        "Biu",
        "Chibok",
        "Damboa",
        "Dikwa",
        "Gubio",
        "Guzamala",
        "Gwoza",
        "Hawul",
        "Jere",
        "Kaga",
        "Kala/Balge",
        "Konduga",
        "Kukawa",
        "Kwaya Kusar",
        "Mafa",
        "Magumeri",
        "Maiduguri",
        "Marte",
        "Mobbar",
        "Monguno",
        "Ngala",
        "Nganzai",
        "Shani"
    ],
    "Cross River": [
        "Abi",
        "Akamkpa",
        "Akpabuyo",
        "Bakassi",
        "Bekwarra",
        "Biase",
        "Boki",
        "Calabar Municipality",
        "Calabar South",
        "Etung",
        "Ikom",
        "Obanliku",
        "Obubra",
        "Obudu",
        "Odukpani",
        "Ogoja",
        "Yakurr",
        "Yala"
    ],
    "Delta": [
        "AniochaN",
        "AniochaS",
        "Bomadi",
        "Burutu",
        "Ethiope West",
        "EthiopeE",
        "IkaNorth",
        "IkaSouth",
        "IsokoNor",
        "IsokoSou",
        "Ndokwa East",
        "Ndokwa West",
        "Okpe",
        "Oshimili North",
        "Oshimili South",
        "Patani",
        "Sapele",
        "Udu",
        "Ughelli North",
        "Ughelli South",
        "Ukwuani",
        "Uvwie",
        "Warri North",
        "Warri South",
        "Warri South-West"
    ],
    "Ebonyi": [
        "Abakalik",
        "Afikpo North",
        "Afikpo South",
        "Ebonyi",
        "Ezza North",
        "Ezza South",
        "Ikwo",
        "Ishielu",
        "Ivo",
        "Izzi",
        "Ohaozara",
        "Ohaukwu",
        "Onicha"
    ],
    "Edo": [
        "Akoko Edo",
        "Egor",
        "Esan Centtral",
        "Esan North East",
        "Esan South East",
        "Esan West",
        "Etsako Central",
        "Etsako East",
        "Etsako West",
        "Igueben",
        "Ikpoba-Okha",
        "Oredo",
        "Orhionmw",
        "Ovia North East",
        "Ovia South West",
        "Owan East",
        "Owan West",
        "Uhunmwonde"
    ],
    "Ekiti": [
        "Ado-Ekiti",
        "Efon",
        "Ekiti East",
        "Ekiti South West",
        "Ekiti West",
        "Emure",
        "Gboyin",
        "Ido-Osi",
        "Ijero",
        "Ikere",
        "Ikole",
        "Ilejemeje",
        "Irepodun-Ifelodun",
        "Ise-Orun",
        "Moba",
        "Oye"
    ],
    "Enugu": [
        "Aninri",
        "Awgu",
        "Enugu East",
        "Enugu North",
        "EnuguSou",
        "Ezeagu",
        "Igbo-Eti",
        "Igbo-eze North",
        "Igbo-eze South",
        "Isi-Uzo",
        "Nkanu East",
        "Nkanu West",
        "Nsukka",
        "Oji-River",
        "Udenu",
        "Udi",
        "Uzo-Uwani"
    ],
    "Gombe": [
        "Akko",
        "Balanga",
        "Billiri",
        "Dukku",
        "Funakaye",
        "Gombe",
        "Kaltungo",
        "Kwami",
        "Nafada",
        "Shomgom",
        "Yalmatu / Deba"
    ],
    "Imo": [
        "Aboh-Mbaise",
        "Ahiazu-Mbaise",
        "Ehime-Mbano",
        "Ezinihitte Mbaise",
        "Ideato North",
        "Ideato South",
        "Ihitte-Uboma Isinweke",
        "Ikeduru",
        "Isiala Mbano",
        "Isu",
        "Mbaitoli",
        "Ngor-Okpala",
        "Njaba",
        "Nkwerre",
        "Nwangele",
        "Obowo",
        "Oguta",
        "Ohaji-Egbema",
        "Okigwe",
        "Orlu",
        "Orsu",
        "Oru-East",
        "Oru-West",
        "Owerri Municipal",
        "Owerri North",
        "Owerri West",
        "Unuimo"
    ],
    "Jigawa": [
        "Auyo",
        "Babura",
        "Biriniwa",
        "Birnin Kudu",
        "Buji",
        "Dutse",
        "Gagarawa",
        "Garki",
        "Gumel",
        "Guri",
        "Gwaram",
        "Gwiwa",
        "Hadejia",
        "Jahun",
        "Kafin Hausa",
        "Kaugama",
        "Kazaure",
        "Kirika Samma",
        "Kiyawa",
        "Maigatari",
        "Malam Mado",
        "Miga",
        "Ringim",
        "Roni",
        "Sule Tankarkar",
        "Taura",
        "Yankwashi"
    ],
    "Kaduna": [
        "Birnin Gwari",
        "Chikun",
        "Giwa",
        "Igabi",
        "Ikara",
        "Jaba",
        "Jema'a",
        "Kachia",
        "Kaduna North",
        "Kaduna South",
        "Kagarko",
        "Kajuru",
        "Kaura",
        "Kauru",
        "Kubau",
        "Kudan",
        "Lere",
        "Makarfi",
        "Sabon Gari",
        "Sanga",
        "Soba",
        "Zangon Kataf",
        "Zaria"
    ],
    "Kano": [
        "Ajingi",
        "Albasu",
        "Bagwai",
        "Bebeji",
        "Bichi",
        "Bunkure",
        "Dala",
        "Dambatta",
        "Dawakin Kudu",
        "Dawakin Tofa",
        "Doguwa",
        "Fagge",
        "Gabasawa",
        "Garko",
        "Garum Mallam",
        "Gaya",
        "Gezawa",
        "Gwale",
        "Gwarzo",
        "Kabo",
        "Kano Municipal",
        "Karaye",
        "Kibiya",
        "Kiru",
        "Kumbotso",
        "Kunchi",
        "Kura",
        "Madobi",
        "Makoda",
        "Minjibir",
        "Nasarawa",
        "Rano",
        "Rimin Gado",
        "Rogo",
        "Shanono",
        "Sumaila",
        "Takai",
        "Tarauni",
        "Tofa",
        "Tsanyawa",
        "Tundun Wada",
        "Ungogo",
        "Warawa",
        "Wudil"
    ],
    "Katsina": [
        "Bakori",
        "Batagarawa",
        "Batsari",
        "Baure",
        "Bindawa",
        "Charanchi",
        "Dandume",
        "Danja",
        "Danmusa",
        "Daura",
        "Dutsi",
        "Dutsin-M",
        "Faskari",
        "Funtua",
        "Ingawa",
        "Jibia",
        "Kafur",
        "Kaita",
        "Kankara",
        "Kankiya",
        "Katsina (K)",
        "Kurfi",
        "Kusada",
        "Mai'Adua",
        "Malumfashi",
        "Mani",
        "Mashi",
        "Matazu",
        "Musawa",
        "Rimi",
        "Sabuwa",
        "Safana",
        "Sandamu",
        "Zango"
    ],
    "Kebbi": [
        "Aleiro",
        "Arewa",
        "Argungu",
        "Augie",
        "Bagudo",
        "Birnin Kebbi",
        "Bunza",
        "Danko Wasagu",
        "Fakai",
        "Gwandu",
        "Jega",
        "Kalgo",
        "Koko/Bes",
        "Maiyama",
        "Ngaski",
        "Sakaba",
        "Shanga",
        "Suru",
        "Yauri",
        "Zuru"
    ],
    "Kogi": [
        "Adavi",
        "Ajaokuta",
        "Ankpa",
        "Bassa",
        "Dekina",
        "Ibaji",
        "Idah",
        "Igalamela-Odolu",
        "Ijumu",
        "Kabba-Bunu",
        "Koton-Karfe",
        "Lokoja",
        "Mopa-Muro",
        "Ofu",
        "Ogori Magongo",
        "Okehi",
        "Okene",
        "Olamaboro",
        "Omala",
        "Yagba East",
        "Yagba West"
    ],
    "Kwara": [
        "Asa",
        "Baruten",
        "Edu",
        "Ekiti",
        "Ifelodun",
        "Ilorin East",
        "Ilorin South",
        "Ilorin West",
        "Irepodun",
        "Isin",
        "Kaiama",
        "Moro",
        "Offa",
        "Oke-Ero",
        "Oyun",
        "Pategi"
    ],
    "Lagos": [
        "Agege",
        "Ajeromi/Ifelodun",
        "Alimosho",
        "Amuwo Odofin",
        "Apapa",
        "Badagary",
        "Epe",
        "Eti-Osa",
        "Ibeju/Lekki",
        "Ifako/Ijaye",
        "Ikeja",
        "Ikorodu",
        "Kosofe",
        "Lagos Island",
        "Lagos Mainland",
        "Mushin",
        "Ojo",
        "Oshodi/Isolo",
        "Shomolu",
        "Surulere"
    ],
    "Nassarawa": [
        "Akwanga",
        "Awe",
        "Doma",
        "Karu",
        "Keana",
        "Keffi",
        "Kokona",
        "Lafia",
        "Nasarawa",
        "Nassarawa Egon",
        "Obi",
        "Toto",
        "Wamba"
    ],
    "Niger": [
        "Agaie",
        "Agwara",
        "Bida",
        "Borgu",
        "Bosso",
        "Chanchaga",
        "Edati",
        "Gbako",
        "Gurara",
        "Katcha",
        "Kontogur",
        "Lapai",
        "Lavun",
        "Magama",
        "Mariga",
        "Mashegu",
        "Mokwa",
        "Muya",
        "Paikoro",
        "Rafi",
        "Rijau",
        "Shiroro",
        "Suleja",
        "Tafa",
        "Wushishi"
    ],
    "Ogun": [
        "Abeokuta North",
        "Abeokuta South",
        "Ado Odo-Ota",
        "Egbado North",
        "Egbado South",
        "Ewekoro",
        "Ifo",
        "Ijebu East",
        "Ijebu North",
        "Ijebu North-East",
        "Ijebu-Ode",
        "Ikenne",
        "Imeko-Afon",
        "Ipokia",
        "Obafemi-Owode",
        "Odeda",
        "Odogbolu",
        "Ogun Waterside",
        "Remo North",
        "Shagamu"
    ],
    "Ondo": [
        "Akoko North-East",
        "Akoko South-East",
        "Akoko South-West",
        "AkokoNorthWest",
        "Akure North",
        "Akure South",
        "Ese-Odo",
        "Idanre",
        "Ifedore",
        "Ilaje",
        "IleOluji/Okeigbo",
        "Irele",
        "Odigbo",
        "Okitipupa",
        "Ondo East",
        "Ondo West",
        "Ose",
        "Owo"
    ],
    "Osun": [
        "Atakumosa East",
        "Atakumosa West",
        "Ayedaade",
        "Ayedire",
        "Boluwaduro",
        "Boripe",
        "Ede North",
        "Ede South",
        "Egbedore",
        "Ejigbo",
        "Ife East",
        "Ife North",
        "Ife South",
        "IfeCentral",
        "Ifedayo",
        "Ifelodun",
        "Ila",
        "Ilesha East",
        "Ilesha West",
        "Irepodun",
        "Irewole",
        "Isokan",
        "Iwo",
        "Obokun",
        "Odo Otin",
        "Ola-Oluwa",
        "Olorunda",
        "Oriade",
        "Orolu",
        "Osogbo"
    ],
    "Oyo": [
        "Afijio",
        "Akinyele",
        "Atiba",
        "Atisbo",
        "Egbeda",
        "Ibadan North",
        "Ibadan North East",
        "Ibadan North West",
        "Ibadan South East",
        "Ibadan South West",
        "Ibarapa Central",
        "Ibarapa East",
        "Ibarapa North",
        "Ido",
        "Irepo",
        "Iseyin",
        "Itesiwaju",
        "Iwajowa",
        "Kajola",
        "Lagelu",
        "Ogbomosho North",
        "Ogbomosho South",
        "Ogo-Oluwa",
        "Olorunsogo",
        "Oluyole",
        "Ona-Ara",
        "Orelope",
        "Ori-Ire",
        "Oyo East",
        "Oyo West",
        "Saki East",
        "Saki West",
        "Surulere"
    ],
    "Plateau": [
        "Barkin Ladi",
        "Bassa",
        "Bokkos",
        "Jos East",
        "Jos North",
        "Jos South",
        "Kanam",
        "Kanke",
        "Langtang North",
        "Langtang South",
        "Mangu",
        "Mikang",
        "Pankshin",
        "Qua'anpa",
        "Riyom",
        "Shendam",
        "Wase"
    ],
    "Rivers": [
        "Abua/Odu",
        "Ahoada East",
        "Ahoada West",
        "Akukutor",
        "Andoni/Odual",
        "Asari-Toru",
        "Bonny",
        "Degema",
        "Eleme",
        "Emuoha",
        "Etche",
        "Gokana",
        "Ikwerre",
        "Khana",
        "Obio/Akpor",
        "Ogba/Egbema/Andoni",
        "Ogu/Bolo",
        "Okrika",
        "Omumma",
        "Opobo/Nkoro",
        "Oyigbo",
        "Port Harcourt",
        "Tai"
    ],
    "Sokoto": [
        "Binji",
        "Bodinga",
        "Dange-Shuni",
        "Gada",
        "Goronyo",
        "Gudu",
        "Gwadabaw",
        "Illela",
        "Isa",
        "Kebbe",
        "Kware",
        "Rabah",
        "Sabon Birni",
        "Shagari",
        "Silame",
        "Sokoto North",
        "Sokoto South",
        "Tambawal",
        "Tangazar",
        "Tureta",
        "Wamakko",
        "Wurno",
        "Yabo"
    ],
    "Taraba": [
        "Ardo-Kola",
        "Bali",
        "Donga",
        "Gashaka",
        "Gassol",
        "Ibi",
        "Jalingo",
        "Karim-Lamido",
        "Kurmi",
        "Lau",
        "Sardauna",
        "Takum",
        "Ussa",
        "Wukari",
        "Yorro",
        "Zing"
    ],
    "Yobe": [
        "Bade",
        "Borsari",
        "Damaturu",
        "Fika",
        "Fune",
        "Geidam",
        "Gujba",
        "Gulani",
        "Jakusko",
        "Karasuwa",
        "Machina",
        "Nangere",
        "Nguru",
        "Potiskum",
        "Tarmuwa",
        "Yunusari",
        "Yusufari"
    ],
    "Zamfara": [
        "Anka",
        "Bakura",
        "Birnin Magaji",
        "Bukkuyum",
        "Bungudu",
        "Gummi",
        "Gusau",
        "Kaura-Namoda",
        "Maradun",
        "Maru",
        "Shinkafi",
        "Talata-Mafara",
        "Tsafe",
        "Zurmi"
    ]
};

const citiesData = {
    "Lagos": [
        "Ajeromi-Ifelodun",
        "Alimosho",
        "Amuwo-Odofin",
        "Apapa",
        "Badagry",
        "Epe",
        "Eti Osa",
        "Ibeju-Lekki",
        "Ifako-Ijaiye",
        "Ikeja",
        "Ikorodu",
        "Kosofe",
        "Lagos Island",
        "Lagos Mainland",
        "Mushin",
        "Ojo",
        "Oshodi-Isolo",
        "Shomolu",
        "Surulere"
    ],
    "Federal Capital Territory": [
        "Bwari",
        "Gwagwalada",
        "Kuje",
        "Kwali",
        "Municipal Area Council"
    ],
    "Oyo": [
        "Akinyele",
        "Atiba",
        "Atisbo",
        "Egbeda",
        "Ibadan North",
        "Ibadan North-East",
        "Ibadan North-West",
        "Ibadan South-East",
        "Ibadan South-West",
        "Ibarapa Central",
        "Ibarapa East",
        "Ibarapa North",
        "Ido",
        "Irepo",
        "Iseyin",
        "Itesiwaju",
        "Iwajowa",
        "Kajola",
        "Lagelu",
        "Ogbomosho North",
        "Ogbomosho South",
        "Ogo Oluwa",
        "Olorunsogo",
        "Oluyole",
        "Ona Ara",
        "Orelope",
        "Ori Ire",
        "Oyo",
        "Oyo East",
        "Saki East",
        "Saki West",
        "Surulere"
    ],
    "Osun": [
        "Atakunmosa West",
        "Aiyedaade",
        "Aiyedire",
        "Boluwaduro",
        "Boripe",
        "Ede North",
        "Ede South",
        "Ife Central",
        "Ife East",
        "Ife North",
        "Ife South",
        "Egbedore",
        "Ejigbo",
        "Ifedayo",
        "Ifelodun",
        "Ila",
        "Ilesa East",
        "Ilesa West",
        "Irepodun",
        "Irewole",
        "Isokan",
        "Iwo",
        "Obokun",
        "Odo Otin",
        "Ola Oluwa",
        "Olorunda",
        "Oriade",
        "Orolu",
        "Osogbo"
    ],
    "Ondo": [
        "Akoko North-West",
        "Akoko South-West",
        "Akoko South-East",
        "Akure North",
        "Akure South",
        "Ese Odo",
        "Idanre",
        "Ifedore",
        "Ilaje",
        "Ile Oluji/Okeigbo",
        "Irele",
        "Odigbo",
        "Okitipupa",
        "Ondo East",
        "Ondo West",
        "Ose",
        "Owo"
    ],
    "Ekiti": [
        "Efon",
        "Ekiti East",
        "Ekiti South-West",
        "Ekiti West",
        "Emure",
        "Gbonyin",
        "Ido Osi",
        "Ijero",
        "Ikere",
        "Ikole",
        "Ilejemeje",
        "Irepodun/Ifelodun",
        "Ise/Orun",
        "Moba",
        "Oye"
    ],
    "Anambra": [
        "Anambra East",
        "Anambra West",
        "Anaocha",
        "Awka North",
        "Awka South",
        "Ayamelum",
        "Dunukofia",
        "Ekwusigo",
        "Idemili North",
        "Idemili South",
        "Ihiala",
        "Njikoka",
        "Nnewi North",
        "Nnewi South",
        "Ogbaru",
        "Onitsha North",
        "Onitsha South",
        "Orumba North",
        "Orumba South",
        "Oyi"
    ],
    "Enugu": [
        "Awgu",
        "Enugu East",
        "Enugu North",
        "Enugu South",
        "Ezeagu",
        "Igbo Etiti",
        "Igbo Eze North",
        "Igbo Eze South",
        "Isi Uzo",
        "Nkanu East",
        "Nkanu West",
        "Nsukka",
        "Oji River",
        "Udenu",
        "Udi",
        "Uzo Uwani"
    ],
    "Abia": [
        "Aba South",
        "Arochukwu",
        "Bende",
        "Ikwuano",
        "Isiala Ngwa North",
        "Isiala Ngwa South",
        "Isuikwuato",
        "Obi Ngwa",
        "Ohafia",
        "Osisioma",
        "Ugwunagbo",
        "Ukwa East",
        "Ukwa West",
        "Umuahia North",
        "Umuahia South",
        "Umu Nneochi"
    ],
    "Imo": [
        "Ahiazu Mbaise",
        "Ehime Mbano",
        "Ezinihitte",
        "Ideato North",
        "Ideato South",
        "Ihitte/Uboma",
        "Ikeduru",
        "Isiala Mbano",
        "Isu",
        "Mbaitoli",
        "Ngor Okpala",
        "Njaba",
        "Nkwerre",
        "Nwangele",
        "Obowo",
        "Oguta",
        "Ohaji/Egbema",
        "Okigwe",
        "Orlu",
        "Orsu",
        "Oru East",
        "Oru West",
        "Owerri Municipal",
        "Owerri North",
        "Owerri West",
        "Unuimo"
    ],
    "Rivers": [
        "Ahoada East",
        "Ahoada West",
        "Akuku-Toru",
        "Andoni",
        "Asari-Toru",
        "Bonny",
        "Degema",
        "Eleme",
        "Emuoha",
        "Etche",
        "Gokana",
        "Ikwerre",
        "Khana",
        "Obio/Akpor",
        "Ogba/Egbema/Ndoni",
        "Ogu/Bolo",
        "Okrika",
        "Omuma",
        "Opobo/Nkoro",
        "Oyigbo",
        "Port Harcourt",
        "Tai"
    ],
    "Kano": [
        "Albasu",
        "Bagwai",
        "Bebeji",
        "Bichi",
        "Bunkure",
        "Dala",
        "Dambatta",
        "Dawakin Kudu",
        "Dawakin Tofa",
        "Doguwa",
        "Fagge",
        "Gabasawa",
        "Garko",
        "Garun Mallam",
        "Gaya",
        "Gezawa",
        "Gwale",
        "Gwarzo",
        "Kabo",
        "Kano Municipal",
        "Karaye",
        "Kibiya",
        "Kiru",
        "Kumbotso",
        "Kunchi",
        "Kura",
        "Madobi",
        "Makoda",
        "Minjibir",
        "Nasarawa",
        "Rano",
        "Rimin Gado",
        "Rogo",
        "Shanono",
        "Sumaila",
        "Takai",
        "Tarauni",
        "Tofa",
        "Tsanyawa",
        "Tudun Wada",
        "Ungogo",
        "Warawa",
        "Wudil"
    ],
    "Kaduna": [
        "Chikun",
        "Giwa",
        "Igabi",
        "Ikara",
        "Jaba",
        "Jema'a",
        "Kachia",
        "Kaduna North",
        "Kaduna South",
        "Kagarko",
        "Kajuru",
        "Kaura",
        "Kauru",
        "Kubau",
        "Kudan",
        "Lere",
        "Makarfi",
        "Sabon Gari",
        "Sanga",
        "Soba",
        "Zangon Kataf",
        "Zaria"
    ],
    "Kwara": [
        "Baruten",
        "Edu",
        "Ekiti",
        "Ifelodun",
        "Ilorin East",
        "Ilorin South",
        "Ilorin West",
        "Irepodun",
        "Isin",
        "Kaiama",
        "Moro",
        "Offa",
        "Oke Ero",
        "Oyun",
        "Pategi"
    ]
}


async function main() {
    // ── States ───────────────────────────────────────────────────────────────────
    const stateCount = await prisma.state.count();
    if (stateCount > 0) {
        console.log(`States already seeded (${stateCount} rows) — skipping.`);
    } else {
        for (const stateData of statesData) {
            await prisma.state.create({
                data: {
                    name: stateData.name,
                    capital: stateData.capital ?? null,
                    latitude: stateData.latitude ?? null,
                    longitude: stateData.longitude ?? null,
                },
            });
        }
        console.log(`Seeded ${statesData.length} states.`);
    }

    // ── Cities ────────────────────────────────────────────────────────────────────
    const cityCount = await prisma.city.count();
    if (cityCount > 0) {
        console.log(`Cities already seeded (${cityCount} rows) — skipping.`);
    } else {
        const allStates = await prisma.state.findMany({ select: { id: true, name: true } });
        const stateNameToId = new Map(allStates.map((s) => [s.name, s.id]));
        // FCT alias used as a key in citiesData
        if (!stateNameToId.has('Federal Capital Territory') && stateNameToId.has('Abuja')) {
            stateNameToId.set('Federal Capital Territory', stateNameToId.get('Abuja')!);
        }

        let totalCities = 0;
        for (const [stateName, cityNames] of Object.entries(citiesData)) {
            const stateId = stateNameToId.get(stateName);
            if (!stateId) {
                console.log(`State not found in DB: "${stateName}" — skipping its cities.`);
                continue;
            }
            for (const cityName of cityNames as string[]) {
                await prisma.city.create({ data: { name: cityName, stateId } });
                totalCities++;
            }
        }
        console.log(`Seeded ${totalCities} cities.`);
    }

    // ── Local Governments ─────────────────────────────────────────────────────────
    const lgCount = await prisma.localGovernment.count();
    if (lgCount > 0) {
        console.log(`Local governments already seeded (${lgCount} rows) — skipping.`);
    } else {
        let totalLgas = 0;
        for (const [, lgas] of Object.entries(localGovernmentsData)) {
            for (const lgName of lgas as string[]) {
                await prisma.localGovernment.create({ data: { name: lgName, cityId: null } });
                totalLgas++;
            }
        }
        console.log(`Seeded ${totalLgas} local governments.`);
    }

    console.log('Seeding complete.');
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
